[package]
name = "drop-storage"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite", "time", "chrono", "offline"] }
slog = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { version = "^1.20", features = ["rt-multi-thread", "macros"] }