[package]
name = "drop-storage"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
sqlx = { git="https://github.com/NordSecurity/sqlx.git", branch="libdrop-compat", features = [ "sqlite", "chrono", "runtime-tokio", "uuid"] }
slog = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }

log = "0.4.19"
[dev-dependencies]
tokio = { version = "^1.20", features = ["rt-multi-thread", "macros"] }
