[package]
name = "drop-analytics"
version = "1.0.0"
edition = "2021"

[dependencies]
slog = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }

[features]
moose = []
moose_file = []
