name: Integration tests
run-name: ${{ github.actor }} is running integration tests
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          default: true        
      - name: docker sdk
        run: |
          pip3 install -r test/requirements.txt 
      - name: Print docker version
        run: docker version
      - name: Build Docker image
        run: docker build -t libdroptestimage test
      - name: Print images
        run: docker images
      - name: run tests
        run: |
          SCENARIO="scenario.*" make -C test
  
